swagger: "2.0"
info:
  version: "0.0.1"
  x-appId: "001"
  title: A simple API Gateway 
# during dev, should point to your local machine
host: www.linyimin.club:8000
# basePath prefixes all resource paths 
basePath: /
# 
schemes:
  # tip: remove http to make production-grade
  - http
  - https
# format of bodies a client can send (Content-Type)
consumes:
  - application/json
# format of the responses to the client (Accepts)
produces:
  - application/json
paths:
  /bookTo:
    # binds a127 app logic to a route
    x-swagger-router-controller: ServiceController
    x-ID: "001"
    x-name: "airlineBookTo"
    get:
      description: 预订往航   班机票
      deprecated: false
      tags:
        - "机票"
      # used as the method name of the controller
      operationId: airlineBookTo
      parameters:
        - name: isBuy
          in: query
          description: 机票购买是否成功，true为成功，false为失败
          required: false
          type: boolean
      responses:
        "200":
          description: Success
          schema:
            # a pointer to a definition
            $ref: "#/definitions/ServiceResponse"
        # responses may fall through to errors
        default:
          description: Error
          schema:
            $ref: "#/definitions/ErrorResponse"
  /refundTo:
    # binds a127 app logic to a route
    x-swagger-router-controller: ServiceController
    x-ID: "002"
    x-name: "airlinerRefundTo"
    get:
      description: 退订往航班机票
      deprecated: false
      tags:
        - "机票"
      # used as the method name of the controller
      operationId: airlineRefundTo
      responses:
        "200":
          description: Success
          schema:
            # a pointer to a definition
            $ref: "#/definitions/ServiceResponse"
        # responses may fall through to errors
        default:
          description: Error
          schema:
            $ref: "#/definitions/ErrorResponse"
  /bookBack:
    # binds a127 app logic to a route
    x-swagger-router-controller: ServiceController
    x-ID: "003"
    x-name: "airlineBookBack"
    get:
      description: 预订返航班机票
      deprecated: false
      tags:
        - "机票"
      # used as the method name of the controller
      operationId: airlineBookBack
      parameters:
        - name: isBuy
          in: query
          description: 机票购买是否成功，true为成功，false为失败
          required: false
          type: boolean
      responses:
        "200":
          description: Success
          schema:
            # a pointer to a definition
            $ref: "#/definitions/ServiceResponse"
        # responses may fall through to errors
        default:
          description: Error
          schema:
            $ref: "#/definitions/ErrorResponse"
  /getService:
    # binds a127 app logic to a route
    x-swagger-router-controller: ServiceController
    x-ID: "004"
    x-name: "getService"
    get:
      description: 获取某类型API信息
      deprecated: false
      tags:
        - "API管理"
      # used as the method name of the controller
      operationId: getService
      parameters:
        - name: tags
          in: query
          description: 指定API的类型,0为机票，1为全部
          required: false
          type: integer
      responses:
        "200":
          description: Success
          schema:
            # a pointer to a definition
            $ref: "#/definitions/ServiceResponse"
        # responses may fall through to errors
        default:
          description: Error
          schema:
            $ref: "#/definitions/ErrorResponse"
  /getServiceByID:
    # binds a127 app logic to a route
    x-swagger-router-controller: ServiceController
    x-ID: "005"
    x-name: "getServiceByID"
    get:
      description: 获取某类型API信息
      deprecated: false
      tags:
        - "API管理"
      # used as the method name of the controller
      operationId: getServiceByID
      parameters:
        - name: ID
          in: query
          description: API的ID
          required: false
          type: string
      responses:
        "200":
          description: Success
          schema:
            # a pointer to a definition
            $ref: "#/definitions/ServiceResponse"
        # responses may fall through to errors
        default:
          description: Error
          schema:
            $ref: "#/definitions/ErrorResponse"
  /swagger:
    x-swagger-pipe: swagger_raw
# complex objects have schema definitions
definitions:
  ServiceResponse:
    required:
      - message
    properties:
      message:
        type: string
  ErrorResponse:
    required:
      - message
    properties:
      message:
        type: string
